### ISSUE TITLE
News/questions/discussions.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#12]
If it's okay with Anton, we could discuss or ask him something in this tap?! 🤔

**Comment by necauqua** [comment]
Well, the discussions are probably bit too much for the github issues (I was ok with requests and even questions, but not discussions).
So I've actually decided to make [my very own Discord server](https://discord.gg/pZrbJNb), huh

Also I am going through exams right now so do not expect me to make anything soon (you weren't already because I did nothing in like two months or so, haha).
And btw Twitter finally unbanned me so I could also tweet something if any update or so happens (the news part)

**Comment by LaytonBaccea** [comment]
Fantastic idea 👍
