### ISSUE TITLE
Moving while growing causes issues.

### ISSUE THREAD

**Issue by HateOnCheeseCake** [necauqua/chiseled-me#2]
If you move during the growing animation there is a high chance you can be teleported into the void. Sometimes only a couple of hundred blocks into the void but other times extremely large into the negative.
![2019-04-22_04 30 08](https://user-images.githubusercontent.com/49850707/56479812-9601bd80-64b7-11e9-9f34-4d39ce617110.png)
No clue what causes it and I have no other mods active. Lastest version.

**Comment by necauqua** [comment]
Received similar report on curse, I'll take a look, thanks for your input :)

Possibly my hackish bytecode injection into the 'move' (now it's called 'travel' btw, huh) method (making the game think you move normally, while actually you're moving more or less depending on the size) is broken because the method was changed a bit in 1.11

**Comment by LaytonBaccea** [comment]
Strange.....  i have never experinced it....

**Comment by necauqua** [comment]
Nah I'm experiencing it all the time when I'm big
Also when you're small and land onto ground there is a little bumping effect
Still trying to find how to fix that all btw

**Comment by buckted** [comment]
Happens to me too
