### ISSUE TITLE
The player's mass should scale with size

### ISSUE THREAD

**Issue by AlaraBread** [necauqua/chiseled-me#29]
Currently, the player gets pushed around by mobs on the ground as though he were the same mass as when he was a normal size.

This is extremely annoying when walking long distances.

This is less noticeable when small, although I think that the player should get pushed more when small.

Your mod does make several mentions to marvel's ant-man, If this is what you are trying to create, consider this: when ant man changes size, his mass stays the same.

So,  you shouldn't implement this if you are looking to make an ant-man mod.

**Comment by necauqua** [comment]
Well yeah, I regret the whole pym stuff, since I wanted to have just a shrinking mod and not an ant-man mod (there are one or two of those).

I will add the multiplier though in next version(s), as this looks like something that should be there for me.

p.s.
but Hank Pym carries a whole tank as his keychain, hey

**Comment by necauqua** [comment]
Fixed in ede2651
