### ISSUE TITLE
Coremod can't patch or whatever with class

### ISSUE THREAD

**Issue by dagobertdu94** [necauqua/chiseled-me#30]
Your coremod Chiseled Me prevents minecraft from starting, I never get the mod loading screen so I need to stop it via task manager. My latest log file is attached to this report and I have no fml-client-latest.log, because I haven't found it.
I am using the latest version of Forge and the latest version of your coremod.

[2020-01-17-3.log](https://github.com/necauqua/chiseled-me/files/4074955/2020-01-17-3.log)

**Comment by necauqua** [comment]
You seem to have other coremods and some of them possibly conflict with the mod
Also it might crash just for you for unknown reasons, because there is some weird bytecode instabilities in the current version.
It is being worked on, so next versions could be better (or worse).

If you don't mind, you can try to find which exact mod causes the conflict and send it here to be added to my list of mods to be checked for conflicts.

(btw this is best achieved by binary search - remove half of the mods except this one and check if it works, if it does - the conflicting mod or set of mods are in the other half, repeat until you find the exact conflicting ones)

**Comment by necauqua** [comment]
Update: now I know what can cause errors like these - its some mod that uses the Mixin library - this is fixed in the current master and should be released in like a week or less - I will ask you to retry this once I release the fixed version.

**Comment by necauqua** [comment]
Likely fixed in beta and no further input - closing this to clean up, feel free to open a new issue if, well, you have any issues
