### ISSUE TITLE
Minecraft crashes on load

### ISSUE THREAD

**Issue by LeeTheKing123** [necauqua/chiseled-me#38]
I dont know why but it crashes on load ethier with the 1.11.2 or the 1.12.2

**Comment by necauqua** [comment]
When you press 'New issue' on GitHub, it gives you a choice from 'Crash report', 'Feature request' and 'Bug report', that is how I configured it.
How do you people keep making those empty issues?

I am saying that because if you've chosen the 'Crash report' it has a template with minimum required information that I need to figure out your exact problem.

Yes, for me the mod crashes too, if I add any other mod from the list of incompatible mods I've made from other crash reports given by people here on GitHub or at the Discord server.

Also it crashes if your Forge version is too old, because I've never set minimum required version so instead of Forge politely asking you to update itself or the mod wont work, it just crashes (with something-something-IRarity in the crashlog iirc).

All this useless rant from me was because you provided exactly zero information, I could not help you right now, at all (except that your problem might be exactly the same as the ones I've listed above).
