### ISSUE TITLE
Game Crashed with other Mods

### ISSUE THREAD

**Issue by NoNaccc** [necauqua/chiseled-me#39]
Hello,
i just made a new Modpack for the Minecraft version 1.12.2 and addet a bunch of mod (list below)
and after I addet the Mod chiseled me the modpack wouldnt start anymore. I looked arround your Github and saw in one Post that you talked about a list of incompatible mods. I looked arround for that list but i couldnt find it. btw the modpack starts fine without the chiseled me mod. 
Would be very happy if you could send me the list of incompatible mods or tell me where i can find it
![image](https://user-images.githubusercontent.com/64231311/80153996-f641a880-85be-11ea-8885-8657192ec070.png)
![image](https://user-images.githubusercontent.com/64231311/80154018-022d6a80-85bf-11ea-8616-97a6842c8f1b.png)

**Comment by necauqua** [comment]
Yeah, the list is not really a physical thing, because when I say 'list of mods' its more like 'I know there is a lot of mods who dont work, and there are issues with exact mods on the github, and when I get to fix all of that I will test for all of them'.

Most notable are OptiFine, iChunUtil (and thus all mods by iChun) and some others from the issues around here.

You have a lot of mods, usually I ask to do a binary search - remove half of the mods, check if it crashes, remove other half - if it crashes with one half and not the other, then the incompatible mod is in that half, repeat the process with only that half, do that until you find the incompatible mod.

This is not really easy to do, and I am sorry for the inconvenience, but yes, since so many mods are incompatible using this mod in modpacks is not really a thing so far.

Usually it is not compatible with so called coremods (it is one of them too) - the mods that change the game internals, for pretty obvious reason - they both tamper with something at the same time and everything breaks.

In earlier forge there was a whole separate 'coremods' folder, but now there isn't, so you can identify such mods by '-Core' suffixes, or by finding 'list of coremods' in logs.

Also yeah, please provide the crashlog, would help so very much.

**Comment by necauqua** [comment]
A lot of mod compat issues are fixed in the current master (releasing it as the next version in about a week) so your issues may or may not be fixed, you may try again with the next release once it is out, but currently I cannot help you without an actual crash.

**Comment by necauqua** [comment]
A crazy ton of mod compat and other issues were resolved in latest discord beta, the mod successfully worked when added to the Project Ozone 3 modpack.
Closing this as stale issue with no further input, feel free to open a new one if you need to.
