### ISSUE TITLE
Super size Recalibrator (SSR)

### ISSUE THREAD

**Issue by MinecrafterDaOne** [necauqua/chiseled-me#42]
No, I am not Asking for a size recalibrator more extreme than the ones you already have, I am asking for a size recalibrator that the player can edit, basically the Player holds the SSR in his/her hand and then the player hits a special key on the keyboard (like I dunno, maybe the \ key) and then the mod brings up a list of all the sizes possible, the player chooses one then exits the list and then proceeds  to use the SSR as a normal size Recalibrator. This Item would have infinite uses/durability.

The SSR would be so OP that limitations would include only being able the be obtained by commands, and creative mode use only kinda like a command block.

Now you are probably thinking that the commands should be able to do that, well there is a slight issue where I can't use the mod's commands at all.

###### Remember this is just a suggestion and you don't need to include this in your mod or follow this suggestion exactly

**Comment by necauqua** [comment]
Well the actual issue is indeed that you cannot use the commands.

The idea is good though, I already thought about something like that.
I am thinking of reworking the content part of the mod, since currently the textures are really bad, and the usability of the recalibrators and stuff it not really great either, so something along the lines of a single recalibrator with different sizes (upgradable maybe? so you'd have the basic one just for like 1/2 and then throw resources at it to become more powerful and get you to 1/16 and beyond) and other things (like throwing away all the 'Pym' references).

**Comment by necauqua** [comment]
Something pretty similar to this is planned to be a replacement for a bunch of dumb items that the mod currently has, and well, in creative it will have a little bit more freedom I guess.

Closing this as part of GitHub issue cleanup process.
