### ISSUE TITLE
Handy tools/advantages when small or big.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#5]
Like when you're small/tiny, you could glide through the air. Or a way to sit on Mobs's/Monster's/Player's shoulder  etc.

And when big, you can grab mobs/monsters/players with your hand and throw/place them.
Or destroy multiple blocks instead of 1 block at a time  etc.

**Comment by necauqua** [comment]
Definitely no sitting on shoulders, mobs/players bbox is just a box (heh), and implementing it all by myself is too much work and the result will not be really great.
For gliding i could perhaps just enable the effect as if you wore an elytra, but thats too much gliding, idk, I'll take a look.

Grabbing-throwing entities is a good idea although this will be hard too, enlargement was actually implemented just because it was easy (just to set number to >1 and a couple of fixes) as a fun quirk, so I don't really want to put much effort into it, this mod is about being small.

Destroying more than one blocks is the easiest part and possibly I'll do something like that.

**Comment by LaytonBaccea** [comment]
Darn it....  could the shoulder thing be in a future update then?, at some time?.
And yes i see that it is mostly about being small or tiny.

Sounds great adding that future when you're big :D

**Comment by necauqua** [comment]
As I've just said somewhere else, definitely no player/entity grabbing.
For gliding you can get at actual elytra, and there are plans to add one more neat way to move faster while being small.

Closing this as part of the big GitHub issues cleanup process.
