### ISSUE TITLE
Crash when using Mohist

### ISSUE THREAD

**Issue by RainEffect** [necauqua/chiseled-me#52]
When I try to use this mod under [Mohist server](https://mohist.red/), server was crashes. 

**Additional information:**
- minecraft version: 1.12.2
- Mohist version: [7bb5453](https://ci.codemc.io/job/Mohist-Community/job/Mohist-1.12.2/615/)
- mod version: 2.0.0.1
- crashlog file or gist: [crash.log](https://github.com/necauqua/chiseled-me/files/4937514/crash.log)

It even can't open any way.

**Comment by necauqua** [comment]
You provided only a couple of lines from the crashlog, and the only thing I can read from it is that something tried to close the game programmatically - usually this is done by something that catched some error and possibly logged it above or below the lines you provided, or maybe Mohist did that - the point is that the exact error you provided seems not really related to this mod.

I am sure that it does not work because of my mod, since it is so fragile atm, but I can't do anything due to lack of info.

And also the mod is being partially rewritten at the moment so in the future this exact crash (or whatever) may not even occur.

**Comment by RainEffect** [comment]
![Crash image](https://user-images.githubusercontent.com/14258727/87812844-66488d80-c893-11ea-903f-7e4ba0dd0b24.png)
Mohist was only return this message, and I translate it.
