### ISSUE TITLE
my game crashes when i try to load it

### ISSUE THREAD

**Issue by SuperSonic392** [necauqua/chiseled-me#59]
is it something with little tiles? forge? creative core? do i have to use chisels and bits?

i haven't been using optifine. (pretty sure i haven't used it in 1.12.2 ever)
is there anything that can fix it.
it says something about IRarity.

if you think anything on my taskbar looks dumb..... why? it's mostly browsers and online games
anyway
![Screenshot (124)](https://user-images.githubusercontent.com/69774065/90346975-e24d0700-dff2-11ea-9fb7-2af1b3525409.png)

what's that all about?

**Comment by necauqua** [comment]
`IRarity` crash means that you have an old Forge, if you update it to last it wont crash because of that.

Right now a ton of fixes are already made and I am releasing a much better version in the next couple of days.
And it includes the fix for this `IRarity` thing, so closing this issue as already fixed.

P.S. Way too many unnecessary question marks and/or questions

**Comment by SuperSonic392** [comment]
the old forge thing explains a whole lot

thanks

**Comment by SuperSonic392** [comment]
" P.S. Way too many unnecessary question marks and/or questions". 
sorry about that.
anyway thanks for that, I'm gonna start getting a newer version of forge now

**Comment by necauqua** [comment]
Don't worry so much, omg
Join our [discord](https://discord.necauqua.dev/) where you can ask anything and get updates about what's up with the update
