### ISSUE TITLE
Possible paths when small or tiny.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#6]
Be able to go through every possible little cracks (bboxes on blocks or something) when you are tiny or small, and perhaps even go under certain blocks when tiny (1/8  -  1/256)  etc.

EDIT: Changed ''(1/512  -  1/4096)'' to ''(1/8  -  1/256)'' .
And ''little cracks when''  to  ''little cracks (bboxes on blocks or something) when''

**Comment by necauqua** [comment]
The game is mostly responsible for that part - i did a couple of hacks like the nether portal and the bed, but overriding most blocks bboxes so that they are more precise - too much unthankful work.
Some mods are precise with their bboxes - for example Chisel&Bits, the main inspiration for this mod in the first place.

Also, what kind of cracks do you want from 16<sup>3</sup> pixels blocks exaclty? :D

**Comment by LaytonBaccea** [comment]
I'm not such of a math fan 😅  .  And yes i tried going under a bed, which is great!! . Could you mention other mods than Chisel&bits (Which i am using with your mod) ?

**Comment by LaytonBaccea** [comment]
Oh i just thought of one!! - Fences and gates, you still can't go through them when you're tiny or small

**Comment by necauqua** [comment]
Minecraft bboxes do not follow models exactly, as I've said.
I could do the same override as with the nether portal block, just for the fences and the fun, huh

**Comment by necauqua** [comment]
Changing more vanilla hitboxes is yet another non-goal(the portal hack is already gone and maybe I should remove the bed one too), however I am (still) planning on making a small mod that will allow you to customize vanilla hitboxes with JSON, just like vanilla did with block models.
