### ISSUE TITLE
Allow small-ish players to use beds.

### ISSUE THREAD

**Issue by CosmicCrowMC** [necauqua/chiseled-me#67]
A small change, but it'd be great if players that are just a little big/small could still use beds. (Maybe 0.75-1.25?)

The reason I'd like this feature is a bit selfish, honestly, but in my "Shrinking Survival" YouTube series, a Lets-Play in which I constantly shrink, it's impossible to move my spawn point since, the tick after I respawn, I shrink. It'd still make sense, though, because as long as players are taller than a block and small enough for their model to fit on the bed, it'd make sense if they could use beds.

**Comment by necauqua** [comment]
I honestly didn't want to bother with sleeping player model so I just disallowed that (as well as riding)
But I could make this a config, sure (but the model will be funky) and maybe later even fix the model so that <=1 size can sleep (why couldn't you sleep if the bed is just the size of a stadion for you? :smile: )

**Comment by necauqua** [comment]
Fixed in ede2651
