### ISSUE TITLE
Autospawn Mobs and Monsters at certain sizes.

### ISSUE THREAD

**Issue by LaytonBaccea** [necauqua/chiseled-me#7]
If it is possible (in a future update).

When you calibrate to 1/16 - 1/256, there are spawning certain mobs and monsters around you, which means there are no places to hide or something like that 🤔  .

EDIT: Changed ''calibrate to 1/512 - 1/4096'' to ''1/16 - 1/256''

**Comment by necauqua** [comment]
Do you mean vanilla mobs or custom micromobs?
Btw at these sizes mobs AI kinda breaks apart so idk.

And yeah, preferable sizes for which this mod was created and works best are 1-1/256, sizes below that are not that useful or good.
It was first developed for 1/16, at 1/256 it still mostly works, and at 1/4096 rendering begins to break apart (you can see little twitching of vertices) because of floating point rounding errors

**Comment by LaytonBaccea** [comment]
Well i mean both, but mainly vanilla mobs and monsters.  But it's still awesome if it could work at those sizes too!! 😄

**Comment by necauqua** [comment]
I've decided that making new specific spawning mechanics is a non-goal of the mod.

The discord beta has gamerules (#14) that allow you to set default size to all entities and/or the player
