### ISSUE TITLE
Camera/bbox misbehavior with Idō Mod

### ISSUE THREAD

**Issue by Alexandqr** [necauqua/chiseled-me#70]
When using Ido's features with this mod installed (such as sneaking, as it changes your z size from 0.85 to 0.75, crawling, like in 1.13+, and swimming), your camera will shake or widen. With larger (or smaller, I couldn't check because Minecraft crashed) sizes, your hitbox also grows to a size Minecraft can't handle, making your game freeze.

1. Install both mods
2. To see basic misbehavior, start sneaking. For others, you have to change your size, or swim.

What should happen is that Ido's bbox changes should be similar to the elytra, as it only changes the z size of the hitbox, not the x or y size.

- Installed mods: There are too many to list (about 152), but I'm pretty sure it doesn't matter, as it only started happening when I installed Ido.
- Forge version: 14.23.5.2847
- Mod version: Latest release, 2.0.0.1 on 1.12.2
- `minecraft_profile_folder/logs/debug.log` file: [debug.log](https://github.com/necauqua/chiseled-me/files/5324914/debug.log) (The file size is 9MB lol, I hope it isn't too hard to read)

I'm not sure if this is going to be fixed, as both mods change the bbox (and most mods that change bboxes don't play well), but I thought I might as well say this has an incompatibility, and in hope that maybe something could be done. And yes, I literally just made this account so I could post this.

**Comment by necauqua** [comment]
No updates of any sorts atm, just writing to show that I noticed and yes, thanks for sharing the incompatibility.

From how you described this I think there might be ways to work around the issue - at least partially, to make it not break completely, just needs testing/checking etc.

**Comment by Alexandqr** [comment]
I see, hopefully this can be fixed after you finish the next update. Keep up the good work!

**Comment by necauqua** [comment]
Ok I am actually going through issues in preparation for finally releasing that crazy good discord beta, and like, what did you expect from the mod that changes the player hitbox as well, huh

Still will try to fix it, actually not a lot of issues for 1.12 left

**Comment by necauqua** [comment]
Ok right now latest beta _mostly_ works nicely with the mod, zero camera issues (especially because I explicitly patched broken camera resize animation that happen with randompatches mod), sneaking and swimming (even when resized) work fine and crawling works fine on normal size, the only weird issues (at least your hitbox is the crawling little cube) arise when you are small and move in 1x1x1 holes, and sometimes hitbox is zero.

For now I guess this is wontfix, camera issues most likely were fixed accidentally with other fixes and the Mixin rewrite and everything.
Feel free to open another issue (or maybe even reopen this one) if you have game-breaking (like unusable camera that you had it seems) issues.
