### ISSUE TITLE
Crash with AstralSorcery

### ISSUE THREAD

**Issue by Duckxz** [necauqua/chiseled-me#73]
When I try to launch the game with chiseled me (version 1.12.2-2.0.0.1), the game crashes.

**Additional information:**
- crashlog file or gist: [crash-2020-11-25_13.43.26-client.txt](https://github.com/necauqua/chiseled-me/files/5596753/crash-2020-11-25_13.43.26-client.txt)

- `minecraft_profile_folder/logs/debug.log` file: [debug.log](https://github.com/necauqua/chiseled-me/files/5596757/debug.log)

**Comment by Duckxz** [comment]
It seems it might be the same as #30

**Comment by LorenzoPapi** [comment]
You seem to have a lot of mods, could you try to see which one conflicts with cm?

**Comment by necauqua** [comment]
Yet again some mod (as well as mine) tried to change the reach distance in the most uncompatible way, Minecraft and/or Forge codebase is eh.

This can (and will) be easily fixed, but yes, name your issues not 'the game just crashes', but 'the game just crashes when I have lots of other mods', hehe

Also you have the llibrary mod which is known (#62) to be incompatible atm, #30 is already fixed in beta

**Comment by necauqua** [comment]
Well this one is AstralSorcery, and it was long fixed in that discord beta

**Comment by necauqua** [comment]
Fixed in ede2651
