### ISSUE TITLE
Combat Reach Doesn't Scale with Size (Better Combat Rebirth & Other Combat Reach Mods)

### ISSUE THREAD

**Issue by Alexandqr** [necauqua/chiseled-me#86]
Here I am again, hi.
This is a bug with the Better Combat Rebirth mod, where your reach (against entities only) doesn't get shorter at smaller scales. Also, the features of BCR don't actually trigger when reaching mobs farther than you normally would at normal size. Basically, the reach BCR uses doesn't scale as it should. A similar problem also occurs with the mod Potion Core, where your reach against other mobs is stuck at normal size, and you can't actually hit anything far away when big (haven't tested if this still persists, but it has happened before)

To reproduce, just use BCR (or similar combat reach changing mod, like Potion Core) and CM together, and change your size. Then just hit some mobs farther than you're supposed to, or outside normal size reach.

Combat reach should scale along with your size.

A lot of mods, but the two important ones are BCR and CM.
Forge Version: 2847
Mod Version: Any, but I used the latest beta.

Didn't actually report this one until now, I found this long ago. Hopefully it doesn't add too much more work before the release.

**Comment by necauqua** [comment]
It is their bug, because they just [hardcoded](https://github.com/SanAndreasP/BetterCombatRebirth/blob/master/src/main/java/bettercombat/mod/client/handler/EventHandlersClient.java#L85) the reach distance (btw wtf is this "longerAttack" config anyway, lol), instead of using the (vanilla!) reach attribute (e.g. `player.getEntityAttribute(EntityPlayer.REACH_DISTANCE).getAttributeValue()` instead of just `5.0`).
This mod does (in the beta atm) scale the attribute, so there is no bug here on my side.

You may ask them to fix that, I am not proactively fixing all the mods :shrug:

This is (almost, because they could've avoided that) the same as asking me to fix modded entities not having their particles scaled, or like any custom logic that depends on distances somehow - the mod tries to ensure that at least vanilla entities and their effects are scaled, weird mod interactions where something will not be scaled are unavoidable.

I try to fix mod compat _crashes_ and fixed that rfp issue on inertia and because it was very easy to do (and not their fault they do not integrate with my mod lol).
